version: '3'

services:
    web:
        image: nginx:alpine
        container_name: webserver_mallowz
        restart: always
        ports:
            - 7072:8000
            - 7000:80
        volumes:
#            - "./web:/var/www/html"
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./site_project/media:/home/site_project/media"
            - "./site_project/static:/home/site_project/static"
        depends_on:
            - django
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_mallowz
        restart: always
        ports:
            - 7070:80
        environment: 
            PMA_HOST: mysql_mallowz
            PMA_ARBITRARY: 1
            MYSQL_ROOT_PASSWORD: "root"
        depends_on:
            - database
    
    database:
        image: mysql:5.7.22
        container_name: mysql_mallowz
        restart: always
        ports:
            - 7071:3306
        volumes:
            - ./data/db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mallowz
            MYSQL_USER: mallowz
            MYSQL_PASSWORD: mallowz

    django:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: django_mallowz
#        command: gunicorn -b 0.0.0.0:8000 -w 4 site_project.wsgi
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - "./site_project:/home/site_project"
            - "./site_project/media:/home/site_project/media"
            - "./site_project/static:/home/site_project/static"
        expose:
            - 8000
        depends_on:
            - database